# Generated by Django 3.2.4 on 2021-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_alter_output_id'),
        ('intoutcome', '0002_alter_intoutcome_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intoutcome',
            name='output',
            field=models.ManyToManyField(to='output.Output'),
        ),
    ]
