# Generated by Django 3.2.4 on 2021-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_last_org_customuser_current_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_org',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Last organization active'),
        ),
    ]
