# Generated by Django 3.2.4 on 2021-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0002_auto_20210706_0718'),
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='outcome',
            field=models.ManyToManyField(to='outcome.Outcome'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Long description of impact'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Short description of impact'),
        ),
    ]
