# Generated by Django 3.2.4 on 2021-07-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0005_remove_project_impact'),
        ('impact', '0002_alter_impact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_project.project'),
        ),
    ]
