# Generated by Django 3.2.4 on 2021-07-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_impact_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='project',
        ),
    ]
