# Generated by Django 3.2.4 on 2021-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0004_remove_outcome_impact'),
        ('impact', '0004_remove_impact_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='outcome',
            field=models.ManyToManyField(to='outcome.Outcome'),
        ),
    ]
