# Generated by Django 3.2.4 on 2021-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_alter_output_id'),
        ('outcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='output',
            field=models.ManyToManyField(blank=True, null=True, to='output.Output'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
