# Generated by Django 3.2.4 on 2021-07-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_impact_project'),
        ('outcome', '0002_alter_outcome_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impact.impact'),
        ),
    ]
