# Generated by Django 3.2.4 on 2021-07-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0003_outcome_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='impact',
        ),
    ]
