# Generated by Django 3.2.4 on 2021-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intoutcome', '0003_intoutcome_output'),
        ('output', '0002_alter_output_id'),
        ('outcome', '0004_remove_outcome_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='intoutcome',
            field=models.ManyToManyField(to='intoutcome.IntOutcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='output',
            field=models.ManyToManyField(to='output.Output'),
        ),
    ]
