# Generated by Django 3.2.4 on 2021-07-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_alter_output_id'),
        ('intoutcome', '0003_intoutcome_output'),
        ('outcome', '0005_auto_20210702_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='intoutcome',
            field=models.ManyToManyField(blank=True, null=True, to='intoutcome.IntOutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='output',
            field=models.ManyToManyField(blank=True, null=True, to='output.Output'),
        ),
    ]
