# Generated by Django 3.2.4 on 2021-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20210726_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorevidence',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Evidence documentation'),
        ),
    ]
