# Generated by Django 3.2.4 on 2021-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_indicatorevidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorevidence',
            name='indicator',
            field=models.ManyToManyField(null=True, related_name='evidence', to='indicator.Indicator'),
        ),
    ]
