# Generated by Django 3.2.4 on 2021-09-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_alter_indicatorevidence_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorevidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Evidence documentation'),
        ),
    ]
