# Generated by Django 3.2.4 on 2022-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_alter_indicatorevidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorevidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidence', verbose_name='Evidence documentation'),
        ),
    ]
