# Generated by Django 3.2.4 on 2021-07-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=1000, verbose_name='Short description of output')),
                ('long_description', models.TextField(verbose_name='Long description of output')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='SEDI', max_length=500, verbose_name='Project name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=1000, verbose_name='Short description of outcome')),
                ('long_description', models.TextField(verbose_name='Long description of outcome')),
                ('output', models.ManyToManyField(blank=True, null=True, to='base_project.Output')),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Short description of impact')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Long description of impact')),
                ('outcome', models.ManyToManyField(blank=True, null=True, to='base_project.Outcome')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_project.impact'),
        ),
    ]
