# Generated by Django 3.2.4 on 2021-07-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_auto_20210706_0718'),
        ('base_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='impact.impact'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Butts', max_length=500, verbose_name='Project name'),
            preserve_default=False,
        ),
    ]
