# Generated by Django 3.2.4 on 2021-07-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0002_auto_20210712_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Long description of project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Short description of project'),
        ),
    ]
