# Generated by Django 3.2.4 on 2021-07-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0002_auto_20210701_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
