# Generated by Django 3.2.4 on 2021-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0002_auto_20210707_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='impact',
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.ManyToManyField(blank=True, null=True, to='base_project.Impact'),
        ),
    ]
