# Generated by Django 3.2.4 on 2021-07-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0003_auto_20210712_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Item type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Long description of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_project.project'),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Short description of Item'),
        ),
    ]
