# Generated by Django 3.2.4 on 2021-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0004_auto_20210712_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='short_description',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='name of Item'),
        ),
    ]
