# Generated by Django 3.2.4 on 2021-07-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0005_auto_20210712_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
    ]
