# Generated by Django 3.2.4 on 2021-07-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0004_remove_impact_project'),
        ('base_project', '0005_remove_project_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='impact.impact'),
        ),
    ]
