# Generated by Django 3.2.4 on 2021-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0007_auto_20210715_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='level_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
