# Generated by Django 3.2.4 on 2021-07-23 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_project', '0009_auto_20210715_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
