# Generated by Django 3.2.4 on 2021-07-26 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_project', '0013_project_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reporter',
            field=models.ManyToManyField(blank=True, null=True, related_name='reporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
