# Generated by Django 3.2.4 on 2021-07-29 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_project', '0014_alter_project_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ManyToManyField(related_name='owner_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='reporter',
            field=models.ManyToManyField(blank=True, null=True, related_name='reporter_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
