# Generated by Django 3.2.4 on 2021-07-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orginvitation',
            old_name='uuid',
            new_name='uid',
        ),
    ]
