# Generated by Django 3.2.4 on 2021-07-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0017_alter_project_organization'),
        ('invitation', '0002_rename_uuid_orginvitation_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_project.organization'),
        ),
    ]
