# Generated by Django 3.2.4 on 2021-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_alter_orginvitation_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvitation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
